services:
  # Бэкенд сервис
  - type: web
    name: qrcodewars-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QR_SECRET_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: qrcodewars-db
          property: connectionString
    autoDeploy: true

  # Фронтенд сервис  
  - type: web
    name: qrcodewars-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://qrcodewars-backend.onrender.com
    autoDeploy: true

databases:
  - name: qrcodewars-db
    plan: free 